### ISSUE TITLE
iHeart Radio

### ISSUE THREAD

**Issue by WillFJS** [MidSpike/iris-utilities#102]
I would love to see iHeart Radio integrated into I.R.I.S I have found a [node package](https://www.npmjs.com/package/iheart) that I think would work great. Take your time on it no need for it right now!

**Comment by MidSpike** [comment]
Thanks for the suggestion, however I will be focusing on fixes and improvements in the following months.

IRIS is already a fairly large bot, and I need to work on cleaning up stuff

**Comment by MidSpike** [comment]
I'll keep this open if I ever get around to doing it

**Comment by WillFJS** [comment]
Alright, sounds good

**Comment by MidSpike** [comment]
Stale issue: closing
