### ISSUE TITLE
Failed to send a packet - Error [UDP_SEND_FAIL]: Tried to send a UDP packet, but there is no socket available.

### ISSUE THREAD

**Issue by MidSpike** [MidSpike/iris-utilities#22]
Intermittent logging of the following:
```
Failed to send a packet - Error [UDP_SEND_FAIL]: Tried to send a UDP packet, but there is no socket available.
```
from
> node_modules\discord.js\src\client\voice\networking\VoiceUDPClient.js
```
VoiceConnectionUDPClient.send
```

**Comment by MidSpike** [comment]
The issue has not presented itself since updating Discord.js to `v12.4.0`

However, I'm going to keep this issue open... just in-case

**Comment by MidSpike** [comment]
It has been a while since this has occurred...

I am going to consider this as possibly fixed

**Comment by sanchir2011** [comment]
Any updates?

**Comment by MidSpike** [comment]
> Any updates?

I found that unusual network interruptions can lead to this occurring.

However this issue is very intermittent

**Comment by MidSpike** [comment]
This issue can only be fixed by exterior methods such as improving network conditions (stability)
