### ISSUE TITLE
Volume lowers back down with looped song.

### ISSUE THREAD

**Issue by Will3126** [MidSpike/iris-utilities#90]
**Describe the bug**
With a looped song in the queue after it loops again the volume resets back down to normal after having it set at 100
**To Reproduce**
Play song,
Set volume
Loop
Wait for the song to end and to play again and hear the volume drop.

**Expected behavior**
volume stays the same for the looped song.
**Screenshots**
N/A

**Additional context**
N/A

**Comment by MidSpike** [comment]
I am unable to reproduce on the current master branch:
![image](https://user-images.githubusercontent.com/22574513/105675504-39ff7080-5eb7-11eb-8f83-181c5aaa090e.png)

Please create a more-detailed step-by-step guide.

**Comment by Will3126** [comment]
Sorry I meant super volume, it was late lol.

**Comment by MidSpike** [comment]
Ah I see.

Super volume is meant to be a funny usage of volume for Super Users.

Along with that in mind; the super volume interface completely bypasses the normal user `VolumeManager` interface.

The resetting of volume (when super volume is applied) is coincidentally an intended feature to prevent the next item in the queue from having super volume applied to it.
