### ISSUE TITLE
Sharding

### ISSUE THREAD

**Issue by MidSpike** [MidSpike/iris-utilities#94]
https://discordjs.guide/sharding/ 

I.R.I.S. needs to be sharded eventually...

If you have any specific knowledge on how to properly shard, please let me know.

**Comment by TH4RDY** [comment]
Hey midspike! This documentation helps alot! I would suggest taking a look, https://discordjs.guide/sharding/

**Comment by MidSpike** [comment]
Sharding is becoming an increasing grueling task...

Although IRIS is currently running 4 shards, there are still plenty of things that need fixing (or refactoring) to *properly* play nicely with shards

**Comment by MidSpike** [comment]
Superseded by #108
